/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesEnabledFeaturesGetResponseSchema = z.object({
    "IsFacilitiesEnabled": z.optional(z.boolean()),
"IsCalendarrEnabled": z.optional(z.boolean())
    })