/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsListResponseSchema = z.object({
    "roomId": z.string(),
"name": z.string(),
"scheduleCount": z.int(),
"updatedAtUtc": z.iso.datetime()
    })