/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsListResponseSchema } from "./temasekWebApiFeaturesRoomsListResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsListEndpoint200Schema = z.array(z.lazy(() => temasekWebApiFeaturesRoomsListResponseSchema))

export const temasekWebApiFeaturesRoomsListEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsListEndpoint200Schema)