/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema } from "./temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema = z.object({
    "roomId": z.string(),
"name": z.string(),
get "schedule"(){
                return z.array(temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema)
              },
"updatedAtUtc": z.iso.datetime()
    })