/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesFormSgCallbackRequestSchema = z.object({
    "clerkUserId": z.string().min(1),
"nric": z.string().min(1),
"name": z.string().min(1)
    })