/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsScheduleStreamEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description No Content
 */
export const temasekWebApiFeaturesRoomsScheduleStreamEndpoint204Schema = z.any()

export const temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleStreamEndpoint204Schema)