/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesFormSgCallbackRequestSchema } from "./temasekWebApiFeaturesFormSgCallbackRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description No Content
 */
export const temasekWebApiFeaturesFormSgCallbackEndpoint204Schema = z.any()

export const temasekWebApiFeaturesFormSgCallbackEndpointMutationRequestSchema = z.lazy(() => temasekWebApiFeaturesFormSgCallbackRequestSchema)

export const temasekWebApiFeaturesFormSgCallbackEndpointMutationResponseSchema = z.lazy(() => temasekWebApiFeaturesFormSgCallbackEndpoint204Schema)