/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardStreamEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description No Content
 */
export const temasekWebApiFeaturesRoomsSignboardStreamEndpoint204Schema = z.any()

export const temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardStreamEndpoint204Schema)