/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesFormSgValidateResponseSchema = z.object({
    "formId": z.string(),
"prefillFieldId": z.string(),
"clerkUserId": z.string()
    })