/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description No Content
 */
export const temasekWebApiFeaturesIndexGetEndpoint204Schema = z.any()

export const temasekWebApiFeaturesIndexGetEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesIndexGetEndpoint204Schema)