/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesFormSgValidateResponseSchema } from "./temasekWebApiFeaturesFormSgValidateResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Success
 */
export const temasekWebApiFeaturesFormSgValidateEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesFormSgValidateResponseSchema)

/**
 * @description Unauthorized
 */
export const temasekWebApiFeaturesFormSgValidateEndpoint401Schema = z.any()

export const temasekWebApiFeaturesFormSgValidateEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesFormSgValidateEndpoint200Schema)