/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description No Content
 */
export const temasekWebApiFeaturesPokedexListEndpoint204Schema = z.any()

/**
 * @description Unauthorized
 */
export const temasekWebApiFeaturesPokedexListEndpoint401Schema = z.any()

export const temasekWebApiFeaturesPokedexListEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesPokedexListEndpoint204Schema)