/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesEnabledFeaturesGetResponseSchema = z.object({
    "isFacilitiesEnabled": z.boolean(),
"isCalendarrEnabled": z.boolean()
    })