/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesEnabledFeaturesGetResponseSchema } from "./temasekWebApiFeaturesEnabledFeaturesGetResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Success
 */
export const temasekWebApiFeaturesEnabledFeaturesGetEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesEnabledFeaturesGetResponseSchema)

export const temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesEnabledFeaturesGetEndpoint200Schema)