/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema } from "./temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsScheduleUpdateRequestSchema = z.object({
    "name": z.string().nullish(),
get "schedule"(){
                return z.array(temasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDtoSchema)
              }
    })