/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsCreateRequestSchema = z.object({
    "roomId": z.string(),
"name": z.string().nullish()
    })