/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema } from "./temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardUpdateRequestSchema = z.object({
    "name": z.string().nullish(),
get "schedule"(){
                return z.array(temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema)
              }
    })