/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema } from "./temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema.ts";
import { temasekWebApiFeaturesRoomsScheduleUpdateRequestSchema } from "./temasekWebApiFeaturesRoomsScheduleUpdateRequestSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsScheduleUpdateEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema)

export const temasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequestSchema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleUpdateRequestSchema)

export const temasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleUpdateEndpoint200Schema)