/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema } from "./temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsScheduleGetEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsScheduleGetEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponseSchema)

export const temasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsScheduleGetEndpoint200Schema)