/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema } from "./temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema.ts";
import { temasekWebApiFeaturesRoomsSignboardUpdateRequestSchema } from "./temasekWebApiFeaturesRoomsSignboardUpdateRequestSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsSignboardUpdateEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema)

export const temasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequestSchema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardUpdateRequestSchema)

export const temasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardUpdateEndpoint200Schema)