/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsCreateRequestSchema } from "./temasekWebApiFeaturesRoomsCreateRequestSchema.ts";
import { temasekWebApiFeaturesRoomsCreateResponseSchema } from "./temasekWebApiFeaturesRoomsCreateResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsCreateEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesRoomsCreateResponseSchema)

export const temasekWebApiFeaturesRoomsCreateEndpointMutationRequestSchema = z.lazy(() => temasekWebApiFeaturesRoomsCreateRequestSchema)

export const temasekWebApiFeaturesRoomsCreateEndpointMutationResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsCreateEndpoint200Schema)