/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema } from "./temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema = z.object({
    "roomId": z.string(),
"name": z.string(),
get "schedule"(){
                return z.array(temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema)
              },
"updatedAtUtc": z.iso.datetime()
    })