/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDtoSchema = z.object({
    "id": z.string(),
"title": z.string(),
"start": z.string(),
"end": z.string(),
"personnel": z.string(),
"location": z.string()
    })