/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema } from "./temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema.ts";
import { z } from "zod/v4";

export const temasekWebApiFeaturesRoomsSignboardGetEndpointPathParamsSchema = z.object({
    "roomId": z.string()
    })

/**
 * @description Success
 */
export const temasekWebApiFeaturesRoomsSignboardGetEndpoint200Schema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponseSchema)

export const temasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponseSchema = z.lazy(() => temasekWebApiFeaturesRoomsSignboardGetEndpoint200Schema)