/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200, TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesEnabledFeaturesGetEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesEnabledFeaturesGetResponse } from "./createTemasekWebApiFeaturesEnabledFeaturesGetResponse.ts";

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesEnabledFeaturesGetEndpoint200(data?: Partial<TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200>): TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200 {

  return createTemasekWebApiFeaturesEnabledFeaturesGetResponse(data)
}

export function createTemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse>): TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesEnabledFeaturesGetEndpoint200()])
}