/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest, TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse } from "../types/TemasekWebApiFeaturesFormSgCallbackEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesFormSgCallbackRequest } from "./createTemasekWebApiFeaturesFormSgCallbackRequest.ts";

/**
 * @description No Content
 */
export function createTemasekWebApiFeaturesFormSgCallbackEndpoint204() {

  return undefined
}

export function createTemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest(data?: Partial<TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest>): TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest {

  return createTemasekWebApiFeaturesFormSgCallbackRequest(data)
}

export function createTemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse(data?: Partial<TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse>): TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesFormSgCallbackEndpoint204()])
}