/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardUpdateRequest } from "../types/TemasekWebApiFeaturesRoomsSignboardUpdateRequest.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto } from "./createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto.ts";

export function createTemasekWebApiFeaturesRoomsSignboardUpdateRequest(data?: Partial<TemasekWebApiFeaturesRoomsSignboardUpdateRequest>): TemasekWebApiFeaturesRoomsSignboardUpdateRequest {

  return {
    ...{"name": faker.string.alpha(),"schedule": faker.helpers.multiple(() => (createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto()))},
    ...data || {}
  }
}