/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse } from "./createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse.ts";
import { createTemasekWebApiFeaturesRoomsScheduleUpdateRequest } from "./createTemasekWebApiFeaturesRoomsScheduleUpdateRequest.ts";

export function createTemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams>): TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200(data?: Partial<TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200>): TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200 {

  return createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse(data)
}

export function createTemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest(data?: Partial<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest>): TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest {

  return createTemasekWebApiFeaturesRoomsScheduleUpdateRequest(data)
}

export function createTemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse(data?: Partial<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse>): TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200()])
}