/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams, TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleStreamEndpoint.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams>): TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description No Content
 */
export function createTemasekWebApiFeaturesRoomsScheduleStreamEndpoint204() {

  return undefined
}

export function createTemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse>): TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsScheduleStreamEndpoint204()])
}