/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesEnabledFeaturesGetResponse } from "../types/TemasekWebApiFeaturesEnabledFeaturesGetResponse.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesEnabledFeaturesGetResponse(data?: Partial<TemasekWebApiFeaturesEnabledFeaturesGetResponse>): TemasekWebApiFeaturesEnabledFeaturesGetResponse {

  return {
    ...{"IsFacilitiesEnabled": faker.datatype.boolean(),"IsCalendarrEnabled": faker.datatype.boolean()},
    ...data || {}
  }
}