/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse } from "./createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse.ts";
import { createTemasekWebApiFeaturesRoomsSignboardUpdateRequest } from "./createTemasekWebApiFeaturesRoomsSignboardUpdateRequest.ts";

export function createTemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams>): TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200(data?: Partial<TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200>): TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200 {

  return createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse(data)
}

export function createTemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest(data?: Partial<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest>): TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest {

  return createTemasekWebApiFeaturesRoomsSignboardUpdateRequest(data)
}

export function createTemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse(data?: Partial<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse>): TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200()])
}