/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsCreateEndpoint200, TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest, TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse } from "../types/TemasekWebApiFeaturesRoomsCreateEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsCreateRequest } from "./createTemasekWebApiFeaturesRoomsCreateRequest.ts";
import { createTemasekWebApiFeaturesRoomsCreateResponse } from "./createTemasekWebApiFeaturesRoomsCreateResponse.ts";

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsCreateEndpoint200(data?: Partial<TemasekWebApiFeaturesRoomsCreateEndpoint200>): TemasekWebApiFeaturesRoomsCreateEndpoint200 {

  return createTemasekWebApiFeaturesRoomsCreateResponse(data)
}

export function createTemasekWebApiFeaturesRoomsCreateEndpointMutationRequest(data?: Partial<TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest>): TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest {

  return createTemasekWebApiFeaturesRoomsCreateRequest(data)
}

export function createTemasekWebApiFeaturesRoomsCreateEndpointMutationResponse(data?: Partial<TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse>): TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsCreateEndpoint200()])
}