/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleUpdateRequest } from "../types/TemasekWebApiFeaturesRoomsScheduleUpdateRequest.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto } from "./createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto.ts";

export function createTemasekWebApiFeaturesRoomsScheduleUpdateRequest(data?: Partial<TemasekWebApiFeaturesRoomsScheduleUpdateRequest>): TemasekWebApiFeaturesRoomsScheduleUpdateRequest {

  return {
    ...{"name": faker.string.alpha(),"schedule": faker.helpers.multiple(() => (createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto()))},
    ...data || {}
  }
}