/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgCallbackRequest } from "../types/TemasekWebApiFeaturesFormSgCallbackRequest.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesFormSgCallbackRequest(data?: Partial<TemasekWebApiFeaturesFormSgCallbackRequest>): TemasekWebApiFeaturesFormSgCallbackRequest {

  return {
    ...{"clerkUserId": faker.string.alpha({ length: 1 }),"nric": faker.string.alpha({ length: 1 }),"name": faker.string.alpha({ length: 1 })},
    ...data || {}
  }
}