/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgValidateEndpoint200, TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse } from "../types/TemasekWebApiFeaturesFormSgValidateEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesFormSgValidateResponse } from "./createTemasekWebApiFeaturesFormSgValidateResponse.ts";

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesFormSgValidateEndpoint200(data?: Partial<TemasekWebApiFeaturesFormSgValidateEndpoint200>): TemasekWebApiFeaturesFormSgValidateEndpoint200 {

  return createTemasekWebApiFeaturesFormSgValidateResponse(data)
}

/**
 * @description Unauthorized
 */
export function createTemasekWebApiFeaturesFormSgValidateEndpoint401() {

  return undefined
}

export function createTemasekWebApiFeaturesFormSgValidateEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse>): TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesFormSgValidateEndpoint200()])
}