/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleGetEndpoint200, TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams, TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleGetEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse } from "./createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse.ts";

export function createTemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams>): TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsScheduleGetEndpoint200(data?: Partial<TemasekWebApiFeaturesRoomsScheduleGetEndpoint200>): TemasekWebApiFeaturesRoomsScheduleGetEndpoint200 {

  return createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse(data)
}

export function createTemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse>): TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsScheduleGetEndpoint200()])
}