/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsListResponse } from "../types/TemasekWebApiFeaturesRoomsListResponse.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsListResponse(data?: Partial<TemasekWebApiFeaturesRoomsListResponse>): TemasekWebApiFeaturesRoomsListResponse {

  return {
    ...{"roomId": faker.string.alpha(),"name": faker.string.alpha(),"scheduleCount": faker.number.int(),"updatedAtUtc": faker.date.anytime().toISOString()},
    ...data || {}
  }
}