/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto } from "./createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto.ts";

export function createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse(data?: Partial<TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse>): TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse {

  return {
    ...{"roomId": faker.string.alpha(),"name": faker.string.alpha(),"schedule": faker.helpers.multiple(() => (createTemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto())),"updatedAtUtc": faker.date.anytime().toISOString()},
    ...data || {}
  }
}