/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsCreateResponse } from "../types/TemasekWebApiFeaturesRoomsCreateResponse.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsCreateResponse(data?: Partial<TemasekWebApiFeaturesRoomsCreateResponse>): TemasekWebApiFeaturesRoomsCreateResponse {

  return {
    ...{"roomId": faker.string.alpha(),"name": faker.string.alpha(),"scheduleCount": faker.number.int(),"updatedAtUtc": faker.date.anytime().toISOString()},
    ...data || {}
  }
}