/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsCreateRequest } from "../types/TemasekWebApiFeaturesRoomsCreateRequest.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsCreateRequest(data?: Partial<TemasekWebApiFeaturesRoomsCreateRequest>): TemasekWebApiFeaturesRoomsCreateRequest {

  return {
    ...{"roomId": faker.string.alpha(),"name": faker.string.alpha()},
    ...data || {}
  }
}