/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams, TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardStreamEndpoint.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams>): TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description No Content
 */
export function createTemasekWebApiFeaturesRoomsSignboardStreamEndpoint204() {

  return undefined
}

export function createTemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse>): TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsSignboardStreamEndpoint204()])
}