/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto } from "../types/TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto(data?: Partial<TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto>): TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto {

  return {
    ...{"id": faker.string.alpha(),"title": faker.string.alpha(),"start": faker.string.alpha(),"end": faker.string.alpha(),"personnel": faker.string.alpha(),"location": faker.string.alpha()},
    ...data || {}
  }
}