/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto } from "./createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto.ts";

export function createTemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse(data?: Partial<TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse>): TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse {

  return {
    ...{"roomId": faker.string.alpha(),"name": faker.string.alpha(),"schedule": faker.helpers.multiple(() => (createTemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto())),"updatedAtUtc": faker.date.anytime().toISOString()},
    ...data || {}
  }
}