/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgValidateResponse } from "../types/TemasekWebApiFeaturesFormSgValidateResponse.ts";
import { faker } from "@faker-js/faker";

export function createTemasekWebApiFeaturesFormSgValidateResponse(data?: Partial<TemasekWebApiFeaturesFormSgValidateResponse>): TemasekWebApiFeaturesFormSgValidateResponse {

  return {
    ...{"formId": faker.string.alpha(),"prefillFieldId": faker.string.alpha(),"clerkUserId": faker.string.alpha()},
    ...data || {}
  }
}