/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesIndexGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesIndexGetEndpoint.ts";
import { faker } from "@faker-js/faker";

/**
 * @description No Content
 */
export function createTemasekWebApiFeaturesIndexGetEndpoint204() {

  return undefined
}

export function createTemasekWebApiFeaturesIndexGetEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesIndexGetEndpointQueryResponse>): TemasekWebApiFeaturesIndexGetEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesIndexGetEndpoint204()])
}