/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesPokedexListEndpointQueryResponse } from "../types/TemasekWebApiFeaturesPokedexListEndpoint.ts";
import { faker } from "@faker-js/faker";

/**
 * @description No Content
 */
export function createTemasekWebApiFeaturesPokedexListEndpoint204() {

  return undefined
}

/**
 * @description Unauthorized
 */
export function createTemasekWebApiFeaturesPokedexListEndpoint401() {

  return undefined
}

export function createTemasekWebApiFeaturesPokedexListEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesPokedexListEndpointQueryResponse>): TemasekWebApiFeaturesPokedexListEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesPokedexListEndpoint204()])
}