/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsListEndpoint200, TemasekWebApiFeaturesRoomsListEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsListEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsListResponse } from "./createTemasekWebApiFeaturesRoomsListResponse.ts";

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsListEndpoint200(data?: TemasekWebApiFeaturesRoomsListEndpoint200): TemasekWebApiFeaturesRoomsListEndpoint200 {

  return [
        ...faker.helpers.multiple(() => (createTemasekWebApiFeaturesRoomsListResponse())),
        ...data || []
      ]
}

export function createTemasekWebApiFeaturesRoomsListEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesRoomsListEndpointQueryResponse>): TemasekWebApiFeaturesRoomsListEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsListEndpoint200()])
}