/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardGetEndpoint200, TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams, TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardGetEndpoint.ts";
import { faker } from "@faker-js/faker";
import { createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse } from "./createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse.ts";

export function createTemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams(data?: Partial<TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams>): TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams {

  return {
    ...{"roomId": faker.string.alpha()},
    ...data || {}
  }
}

/**
 * @description Success
 */
export function createTemasekWebApiFeaturesRoomsSignboardGetEndpoint200(data?: Partial<TemasekWebApiFeaturesRoomsSignboardGetEndpoint200>): TemasekWebApiFeaturesRoomsSignboardGetEndpoint200 {

  return createTemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse(data)
}

export function createTemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse(data?: Partial<TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse>): TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse {

  return data || faker.helpers.arrayElement<any>([createTemasekWebApiFeaturesRoomsSignboardGetEndpoint200()])
}