/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesEnabledFeaturesGetEndpoint.ts";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey = () => [{ url: '/api/enabled-features' }] as const

export type TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey>

/**
 * {@link /api/enabled-features}
 */
export async function temasekWebApiFeaturesEnabledFeaturesGetEndpoint(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/enabled-features`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey()
        return queryOptions<TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, typeof queryKey>({
        
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesEnabledFeaturesGetEndpoint({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/enabled-features}
 */
export function useTemasekWebApiFeaturesEnabledFeaturesGetEndpoint<TData = TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey>(options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryKey()

         const query = useQuery({
          ...temasekWebApiFeaturesEnabledFeaturesGetEndpointQueryOptions(config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}