/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesPokedexListEndpointQueryResponse, TemasekWebApiFeaturesPokedexListEndpoint401 } from "../types/TemasekWebApiFeaturesPokedexListEndpoint.ts";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesPokedexListEndpointQueryKey = () => [{ url: '/pokedex' }] as const

export type TemasekWebApiFeaturesPokedexListEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesPokedexListEndpointQueryKey>

/**
 * {@link /pokedex}
 */
export async function temasekWebApiFeaturesPokedexListEndpoint(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesPokedexListEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesPokedexListEndpoint401>, unknown>({ method : "GET", url : `/pokedex`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesPokedexListEndpointQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesPokedexListEndpointQueryKey()
        return queryOptions<TemasekWebApiFeaturesPokedexListEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesPokedexListEndpoint401>, TemasekWebApiFeaturesPokedexListEndpointQueryResponse, typeof queryKey>({
        
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesPokedexListEndpoint({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /pokedex}
 */
export function useTemasekWebApiFeaturesPokedexListEndpoint<TData = TemasekWebApiFeaturesPokedexListEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesPokedexListEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesPokedexListEndpointQueryKey>(options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesPokedexListEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesPokedexListEndpoint401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesPokedexListEndpointQueryKey()

         const query = useQuery({
          ...temasekWebApiFeaturesPokedexListEndpointQueryOptions(config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesPokedexListEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesPokedexListEndpoint401>, TData, TemasekWebApiFeaturesPokedexListEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<TemasekWebApiFeaturesPokedexListEndpoint401>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}