/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesIndexGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesIndexGetEndpoint.ts";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesIndexGetEndpointQueryKey = () => [{ url: '/api' }] as const

export type TemasekWebApiFeaturesIndexGetEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesIndexGetEndpointQueryKey>

/**
 * {@link /api}
 */
export async function temasekWebApiFeaturesIndexGetEndpoint(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesIndexGetEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesIndexGetEndpointQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesIndexGetEndpointQueryKey()
        return queryOptions<TemasekWebApiFeaturesIndexGetEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesIndexGetEndpointQueryResponse, typeof queryKey>({
        
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesIndexGetEndpoint({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api}
 */
export function useTemasekWebApiFeaturesIndexGetEndpoint<TData = TemasekWebApiFeaturesIndexGetEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesIndexGetEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesIndexGetEndpointQueryKey>(options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesIndexGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesIndexGetEndpointQueryKey()

         const query = useQuery({
          ...temasekWebApiFeaturesIndexGetEndpointQueryOptions(config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesIndexGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesIndexGetEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}