/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const temasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationKey = () => [{ url: '/api/rooms/:roomId/schedule' }] as const

export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationKey = ReturnType<typeof temasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationKey>

/**
 * {@link /api/rooms/:roomId/schedule}
 */
export async function temasekWebApiFeaturesRoomsScheduleUpdateEndpoint(roomId: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams["roomId"], data: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest, config: Partial<RequestConfig<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest>({ method : "PUT", url : `/api/rooms/${roomId}/schedule`, data : requestData, ... requestConfig })
  return res.data
}

/**
 * {@link /api/rooms/:roomId/schedule}
 */
export function useTemasekWebApiFeaturesRoomsScheduleUpdateEndpoint<TContext>(options: 
{
  mutation?: MutationObserverOptions<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, {roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams["roomId"]>, data: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? temasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationKey()

          return useMutation<TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, {roomId: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams["roomId"], data: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest}, TContext>({
            mutationFn: async({ roomId, data }) => {
              return temasekWebApiFeaturesRoomsScheduleUpdateEndpoint(roomId, data, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)
      
}
