/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsScheduleGetEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey = (roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams["roomId"]>) => [{ url: '/api/rooms/:roomId/schedule', params: {roomId:roomId} }] as const

export type TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey>

/**
 * {@link /api/rooms/:roomId/schedule}
 */
export async function temasekWebApiFeaturesRoomsScheduleGetEndpoint(roomId: TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams["roomId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/rooms/${roomId}/schedule`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesRoomsScheduleGetEndpointQueryOptions(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams["roomId"]>, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey(roomId)
        return queryOptions<TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, typeof queryKey>({
        enabled: !!(roomId),
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesRoomsScheduleGetEndpoint(toValue(roomId), { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/rooms/:roomId/schedule}
 */
export function useTemasekWebApiFeaturesRoomsScheduleGetEndpoint<TData = TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey>(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams["roomId"]>, options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesRoomsScheduleGetEndpointQueryKey(roomId)

         const query = useQuery({
          ...temasekWebApiFeaturesRoomsScheduleGetEndpointQueryOptions(roomId, config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}
