/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest, TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse } from "../types/TemasekWebApiFeaturesRoomsCreateEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const temasekWebApiFeaturesRoomsCreateEndpointMutationKey = () => [{ url: '/api/rooms' }] as const

export type TemasekWebApiFeaturesRoomsCreateEndpointMutationKey = ReturnType<typeof temasekWebApiFeaturesRoomsCreateEndpointMutationKey>

/**
 * {@link /api/rooms}
 */
export async function temasekWebApiFeaturesRoomsCreateEndpoint(data: TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest, config: Partial<RequestConfig<TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest>({ method : "POST", url : `/api/rooms`, data : requestData, ... requestConfig })
  return res.data
}

/**
 * {@link /api/rooms}
 */
export function useTemasekWebApiFeaturesRoomsCreateEndpoint<TContext>(options: 
{
  mutation?: MutationObserverOptions<TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse, ResponseErrorConfig<Error>, {data: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? temasekWebApiFeaturesRoomsCreateEndpointMutationKey()

          return useMutation<TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse, ResponseErrorConfig<Error>, {data: TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest}, TContext>({
            mutationFn: async({ data }) => {
              return temasekWebApiFeaturesRoomsCreateEndpoint(data, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)
      
}