/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsListEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsListEndpoint.ts";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesRoomsListEndpointQueryKey = () => [{ url: '/api/rooms' }] as const

export type TemasekWebApiFeaturesRoomsListEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesRoomsListEndpointQueryKey>

/**
 * {@link /api/rooms}
 */
export async function temasekWebApiFeaturesRoomsListEndpoint(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesRoomsListEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/rooms`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesRoomsListEndpointQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesRoomsListEndpointQueryKey()
        return queryOptions<TemasekWebApiFeaturesRoomsListEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsListEndpointQueryResponse, typeof queryKey>({
        
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesRoomsListEndpoint({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/rooms}
 */
export function useTemasekWebApiFeaturesRoomsListEndpoint<TData = TemasekWebApiFeaturesRoomsListEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesRoomsListEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesRoomsListEndpointQueryKey>(options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesRoomsListEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesRoomsListEndpointQueryKey()

         const query = useQuery({
          ...temasekWebApiFeaturesRoomsListEndpointQueryOptions(config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesRoomsListEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesRoomsListEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}