/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const temasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationKey = () => [{ url: '/rooms/:roomId/signboard' }] as const

export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationKey = ReturnType<typeof temasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationKey>

/**
 * {@link /rooms/:roomId/signboard}
 */
export async function temasekWebApiFeaturesRoomsSignboardUpdateEndpoint(roomId: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams["roomId"], data: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest, config: Partial<RequestConfig<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest>({ method : "PUT", url : `/rooms/${roomId}/signboard`, data : requestData, ... requestConfig })
  return res.data
}

/**
 * {@link /rooms/:roomId/signboard}
 */
export function useTemasekWebApiFeaturesRoomsSignboardUpdateEndpoint<TContext>(options: 
{
  mutation?: MutationObserverOptions<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, {roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams["roomId"]>, data: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? temasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationKey()

          return useMutation<TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse, ResponseErrorConfig<Error>, {roomId: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams["roomId"], data: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest}, TContext>({
            mutationFn: async({ roomId, data }) => {
              return temasekWebApiFeaturesRoomsSignboardUpdateEndpoint(roomId, data, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)
      
}