/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsSignboardStreamEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey = (roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams["roomId"]>) => [{ url: '/rooms/:roomId/signboard/stream', params: {roomId:roomId} }] as const

export type TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey>

/**
 * {@link /rooms/:roomId/signboard/stream}
 */
export async function temasekWebApiFeaturesRoomsSignboardStreamEndpoint(roomId: TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams["roomId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/rooms/${roomId}/signboard/stream`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryOptions(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams["roomId"]>, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey(roomId)
        return queryOptions<TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, typeof queryKey>({
        enabled: !!(roomId),
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesRoomsSignboardStreamEndpoint(toValue(roomId), { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /rooms/:roomId/signboard/stream}
 */
export function useTemasekWebApiFeaturesRoomsSignboardStreamEndpoint<TData = TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey>(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams["roomId"]>, options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryKey(roomId)

         const query = useQuery({
          ...temasekWebApiFeaturesRoomsSignboardStreamEndpointQueryOptions(roomId, config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}