/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest, TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse } from "../types/TemasekWebApiFeaturesFormSgCallbackEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const temasekWebApiFeaturesFormSgCallbackEndpointMutationKey = () => [{ url: '/formsg/callback' }] as const

export type TemasekWebApiFeaturesFormSgCallbackEndpointMutationKey = ReturnType<typeof temasekWebApiFeaturesFormSgCallbackEndpointMutationKey>

/**
 * {@link /formsg/callback}
 */
export async function temasekWebApiFeaturesFormSgCallbackEndpoint(data: TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest, config: Partial<RequestConfig<TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest>({ method : "POST", url : `/formsg/callback`, data : requestData, ... requestConfig })
  return res.data
}

/**
 * {@link /formsg/callback}
 */
export function useTemasekWebApiFeaturesFormSgCallbackEndpoint<TContext>(options: 
{
  mutation?: MutationObserverOptions<TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse, ResponseErrorConfig<Error>, {data: MaybeRefOrGetter<TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? temasekWebApiFeaturesFormSgCallbackEndpointMutationKey()

          return useMutation<TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse, ResponseErrorConfig<Error>, {data: TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest}, TContext>({
            mutationFn: async({ data }) => {
              return temasekWebApiFeaturesFormSgCallbackEndpoint(data, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)
      
}