/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsScheduleStreamEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey = (roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams["roomId"]>) => [{ url: '/api/rooms/:roomId/schedule/stream', params: {roomId:roomId} }] as const

export type TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey>

/**
 * {@link /api/rooms/:roomId/schedule/stream}
 */
export async function temasekWebApiFeaturesRoomsScheduleStreamEndpoint(roomId: TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams["roomId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/rooms/${roomId}/schedule/stream`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryOptions(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams["roomId"]>, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey(roomId)
        return queryOptions<TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, typeof queryKey>({
        enabled: !!(roomId),
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesRoomsScheduleStreamEndpoint(toValue(roomId), { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/rooms/:roomId/schedule/stream}
 */
export function useTemasekWebApiFeaturesRoomsScheduleStreamEndpoint<TData = TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey>(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams["roomId"]>, options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryKey(roomId)

         const query = useQuery({
          ...temasekWebApiFeaturesRoomsScheduleStreamEndpointQueryOptions(roomId, config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}
