/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams } from "../types/TemasekWebApiFeaturesRoomsSignboardGetEndpoint.ts";
import type { MaybeRefOrGetter } from "vue";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey = (roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams["roomId"]>) => [{ url: '/rooms/:roomId/signboard', params: {roomId:roomId} }] as const

export type TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey>

/**
 * {@link /rooms/:roomId/signboard}
 */
export async function temasekWebApiFeaturesRoomsSignboardGetEndpoint(roomId: TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams["roomId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/rooms/${roomId}/signboard`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesRoomsSignboardGetEndpointQueryOptions(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams["roomId"]>, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey(roomId)
        return queryOptions<TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, ResponseErrorConfig<Error>, TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, typeof queryKey>({
        enabled: !!(roomId),
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesRoomsSignboardGetEndpoint(toValue(roomId), { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /rooms/:roomId/signboard}
 */
export function useTemasekWebApiFeaturesRoomsSignboardGetEndpoint<TData = TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey>(roomId: MaybeRefOrGetter<TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams["roomId"]>, options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesRoomsSignboardGetEndpointQueryKey(roomId)

         const query = useQuery({
          ...temasekWebApiFeaturesRoomsSignboardGetEndpointQueryOptions(roomId, config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}