/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../utils/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../../utils/kubb-client";
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from "@tanstack/vue-query";
import type { TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, TemasekWebApiFeaturesFormSgValidateEndpoint401 } from "../types/TemasekWebApiFeaturesFormSgValidateEndpoint.ts";
import { queryOptions, useQuery } from "@tanstack/vue-query";
import { toValue } from "vue";

export const temasekWebApiFeaturesFormSgValidateEndpointQueryKey = () => [{ url: '/formsg/validate' }] as const

export type TemasekWebApiFeaturesFormSgValidateEndpointQueryKey = ReturnType<typeof temasekWebApiFeaturesFormSgValidateEndpointQueryKey>

/**
 * {@link /formsg/validate}
 */
export async function temasekWebApiFeaturesFormSgValidateEndpoint(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesFormSgValidateEndpoint401>, unknown>({ method : "GET", url : `/formsg/validate`, ... requestConfig })
  return res.data
}

export function temasekWebApiFeaturesFormSgValidateEndpointQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = temasekWebApiFeaturesFormSgValidateEndpointQueryKey()
        return queryOptions<TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesFormSgValidateEndpoint401>, TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, typeof queryKey>({
        
        queryKey,
        queryFn: async ({ signal }) => {
            return temasekWebApiFeaturesFormSgValidateEndpoint({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /formsg/validate}
 */
export function useTemasekWebApiFeaturesFormSgValidateEndpoint<TData = TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, TQueryData = TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, TQueryKey extends QueryKey = TemasekWebApiFeaturesFormSgValidateEndpointQueryKey>(options: 
{
  query?: Partial<UseQueryOptions<TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesFormSgValidateEndpoint401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? temasekWebApiFeaturesFormSgValidateEndpointQueryKey()

         const query = useQuery({
          ...temasekWebApiFeaturesFormSgValidateEndpointQueryOptions(config),
          ...resolvedOptions,
          queryKey
         } as unknown as UseQueryOptions<TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, ResponseErrorConfig<TemasekWebApiFeaturesFormSgValidateEndpoint401>, TData, TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<TemasekWebApiFeaturesFormSgValidateEndpoint401>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}