/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesRoomsCreateRequest = {
    /**
     * @type string
    */
    roomId: string;
    /**
     * @type string
    */
    name?: string | null;
};