/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse } from "./TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse.ts";

export type TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsSignboardGetEndpoint200 = TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse;

export type TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse = TemasekWebApiFeaturesRoomsSignboardGetEndpoint200;

export type TemasekWebApiFeaturesRoomsSignboardGetEndpointQuery = {
    Response: TemasekWebApiFeaturesRoomsSignboardGetEndpoint200;
    PathParams: TemasekWebApiFeaturesRoomsSignboardGetEndpointPathParams;
    Errors: any;
};