/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto } from "./TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto.ts";

export type TemasekWebApiFeaturesRoomsScheduleUpdateRequest = {
    /**
     * @type string
    */
    name?: string | null;
    /**
     * @type array
    */
    schedule: TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto[];
};