/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesEnabledFeaturesGetResponse } from "./TemasekWebApiFeaturesEnabledFeaturesGetResponse.ts";

/**
 * @description Success
*/
export type TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200 = TemasekWebApiFeaturesEnabledFeaturesGetResponse;

export type TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse = TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200;

export type TemasekWebApiFeaturesEnabledFeaturesGetEndpointQuery = {
    Response: TemasekWebApiFeaturesEnabledFeaturesGetEndpoint200;
    Errors: any;
};