/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsListResponse } from "./TemasekWebApiFeaturesRoomsListResponse.ts";

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsListEndpoint200 = TemasekWebApiFeaturesRoomsListResponse[];

export type TemasekWebApiFeaturesRoomsListEndpointQueryResponse = TemasekWebApiFeaturesRoomsListEndpoint200;

export type TemasekWebApiFeaturesRoomsListEndpointQuery = {
    Response: TemasekWebApiFeaturesRoomsListEndpoint200;
    Errors: any;
};