/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesFormSgValidateResponse = {
    /**
     * @type string
    */
    formId: string;
    /**
     * @type string
    */
    prefillFieldId: string;
    /**
     * @type string
    */
    clerkUserId: string;
};