/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesFormSgCallbackRequest = {
    /**
     * @minLength 1
     * @type string
    */
    clerkUserId: string;
    /**
     * @minLength 1
     * @type string
    */
    nric: string;
    /**
     * @minLength 1
     * @type string
    */
    name: string;
};