/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description No Content
*/
export type TemasekWebApiFeaturesRoomsScheduleStreamEndpoint204 = any;

export type TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse = TemasekWebApiFeaturesRoomsScheduleStreamEndpoint204;

export type TemasekWebApiFeaturesRoomsScheduleStreamEndpointQuery = {
    Response: TemasekWebApiFeaturesRoomsScheduleStreamEndpoint204;
    PathParams: TemasekWebApiFeaturesRoomsScheduleStreamEndpointPathParams;
    Errors: any;
};