/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse } from "./TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse.ts";
import type { TemasekWebApiFeaturesRoomsSignboardUpdateRequest } from "./TemasekWebApiFeaturesRoomsSignboardUpdateRequest.ts";

export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200 = TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse;

export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest = TemasekWebApiFeaturesRoomsSignboardUpdateRequest;

export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse = TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200;

export type TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutation = {
    Response: TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint200;
    Request: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationRequest;
    PathParams: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointPathParams;
    Errors: any;
};