/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description No Content
*/
export type TemasekWebApiFeaturesIndexGetEndpoint204 = any;

export type TemasekWebApiFeaturesIndexGetEndpointQueryResponse = TemasekWebApiFeaturesIndexGetEndpoint204;

export type TemasekWebApiFeaturesIndexGetEndpointQuery = {
    Response: TemasekWebApiFeaturesIndexGetEndpoint204;
    Errors: any;
};