/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsCreateRequest } from "./TemasekWebApiFeaturesRoomsCreateRequest.ts";
import type { TemasekWebApiFeaturesRoomsCreateResponse } from "./TemasekWebApiFeaturesRoomsCreateResponse.ts";

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsCreateEndpoint200 = TemasekWebApiFeaturesRoomsCreateResponse;

export type TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest = TemasekWebApiFeaturesRoomsCreateRequest;

export type TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse = TemasekWebApiFeaturesRoomsCreateEndpoint200;

export type TemasekWebApiFeaturesRoomsCreateEndpointMutation = {
    Response: TemasekWebApiFeaturesRoomsCreateEndpoint200;
    Request: TemasekWebApiFeaturesRoomsCreateEndpointMutationRequest;
    Errors: any;
};