/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto } from "./TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto.ts";

export type TemasekWebApiFeaturesRoomsSignboardUpdateRequest = {
    /**
     * @type string
    */
    name?: string | null;
    /**
     * @type array
    */
    schedule: TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto[];
};