/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesEnabledFeaturesGetResponse = {
    /**
     * @type boolean | undefined
    */
    isFacilitiesEnabled?: boolean;
    /**
     * @type boolean | undefined
    */
    isCalendarrEnabled?: boolean;
};