/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesRoomsListResponse = {
    /**
     * @type string
    */
    roomId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type integer, int32
    */
    scheduleCount: number;
    /**
     * @type string, date-time
    */
    updatedAtUtc: string;
};