/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesEnabledFeaturesGetResponse = {
    /**
     * @type boolean
    */
    isFacilitiesEnabled: boolean;
};