/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto } from "./TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto.ts";

export type TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse = {
    /**
     * @type string
    */
    roomId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type array
    */
    schedule: TemasekWebApiFeaturesRoomsScheduleContractsScheduleActivityDto[];
    /**
     * @type string, date-time
    */
    updatedAtUtc: string;
};