/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesEnabledFeaturesGetResponse = {
    /**
     * @type boolean | undefined
    */
    IsFacilitiesEnabled?: boolean;
    /**
     * @type boolean | undefined
    */
    IsCalendarrEnabled?: boolean;
};