/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse } from "./TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse.ts";
import type { TemasekWebApiFeaturesRoomsScheduleUpdateRequest } from "./TemasekWebApiFeaturesRoomsScheduleUpdateRequest.ts";

export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200 = TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse;

export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest = TemasekWebApiFeaturesRoomsScheduleUpdateRequest;

export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse = TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200;

export type TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutation = {
    Response: TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint200;
    Request: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationRequest;
    PathParams: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointPathParams;
    Errors: any;
};