/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgCallbackRequest } from "./TemasekWebApiFeaturesFormSgCallbackRequest.ts";

/**
 * @description No Content
*/
export type TemasekWebApiFeaturesFormSgCallbackEndpoint204 = any;

export type TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest = TemasekWebApiFeaturesFormSgCallbackRequest;

export type TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse = TemasekWebApiFeaturesFormSgCallbackEndpoint204;

export type TemasekWebApiFeaturesFormSgCallbackEndpointMutation = {
    Response: TemasekWebApiFeaturesFormSgCallbackEndpoint204;
    Request: TemasekWebApiFeaturesFormSgCallbackEndpointMutationRequest;
    Errors: any;
};