/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description No Content
*/
export type TemasekWebApiFeaturesPokedexListEndpoint204 = any;

/**
 * @description Unauthorized
*/
export type TemasekWebApiFeaturesPokedexListEndpoint401 = any;

export type TemasekWebApiFeaturesPokedexListEndpointQueryResponse = TemasekWebApiFeaturesPokedexListEndpoint204;

export type TemasekWebApiFeaturesPokedexListEndpointQuery = {
    Response: TemasekWebApiFeaturesPokedexListEndpoint204;
    Errors: TemasekWebApiFeaturesPokedexListEndpoint401;
};