/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse } from "./TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse.ts";

export type TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description Success
*/
export type TemasekWebApiFeaturesRoomsScheduleGetEndpoint200 = TemasekWebApiFeaturesRoomsScheduleContractsRoomScheduleResponse;

export type TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse = TemasekWebApiFeaturesRoomsScheduleGetEndpoint200;

export type TemasekWebApiFeaturesRoomsScheduleGetEndpointQuery = {
    Response: TemasekWebApiFeaturesRoomsScheduleGetEndpoint200;
    PathParams: TemasekWebApiFeaturesRoomsScheduleGetEndpointPathParams;
    Errors: any;
};