/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams = {
    /**
     * @type string
    */
    roomId: string;
};

/**
 * @description No Content
*/
export type TemasekWebApiFeaturesRoomsSignboardStreamEndpoint204 = any;

export type TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse = TemasekWebApiFeaturesRoomsSignboardStreamEndpoint204;

export type TemasekWebApiFeaturesRoomsSignboardStreamEndpointQuery = {
    Response: TemasekWebApiFeaturesRoomsSignboardStreamEndpoint204;
    PathParams: TemasekWebApiFeaturesRoomsSignboardStreamEndpointPathParams;
    Errors: any;
};