/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto } from "./TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto.ts";

export type TemasekWebApiFeaturesRoomsSignboardContractsRoomSignboardResponse = {
    /**
     * @type string
    */
    roomId: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type array
    */
    schedule: TemasekWebApiFeaturesRoomsSignboardContractsSignboardActivityDto[];
    /**
     * @type string, date-time
    */
    updatedAtUtc: string;
};