/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgValidateResponse } from "./TemasekWebApiFeaturesFormSgValidateResponse.ts";

/**
 * @description Success
*/
export type TemasekWebApiFeaturesFormSgValidateEndpoint200 = TemasekWebApiFeaturesFormSgValidateResponse;

/**
 * @description Unauthorized
*/
export type TemasekWebApiFeaturesFormSgValidateEndpoint401 = any;

export type TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse = TemasekWebApiFeaturesFormSgValidateEndpoint200;

export type TemasekWebApiFeaturesFormSgValidateEndpointQuery = {
    Response: TemasekWebApiFeaturesFormSgValidateEndpoint200;
    Errors: TemasekWebApiFeaturesFormSgValidateEndpoint401;
};