/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse, TemasekWebApiFeaturesFormSgValidateEndpoint401 } from "../types/TemasekWebApiFeaturesFormSgValidateEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesFormSgValidateEndpointHandlerResponse200(data: TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesFormSgValidateEndpointHandlerResponse401(data?: TemasekWebApiFeaturesFormSgValidateEndpoint401) {

      return new Response(JSON.stringify(data), {
        status: 401,
        
      })
}

export function temasekWebApiFeaturesFormSgValidateEndpointHandler(data?: TemasekWebApiFeaturesFormSgValidateEndpointQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/formsg/validate`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}