/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsListEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsListEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsListEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsListEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsListEndpointHandler(data?: TemasekWebApiFeaturesRoomsListEndpointQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/rooms`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}