/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardStreamEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsSignboardStreamEndpointHandlerResponse204(data?: TemasekWebApiFeaturesRoomsSignboardStreamEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function temasekWebApiFeaturesRoomsSignboardStreamEndpointHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/rooms/:roomId/signboard/stream`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}