/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse } from "../types/TemasekWebApiFeaturesRoomsCreateEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsCreateEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsCreateEndpointHandler(data?: TemasekWebApiFeaturesRoomsCreateEndpointMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/api/rooms`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}