/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleUpdateEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsScheduleUpdateEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsScheduleUpdateEndpointHandler(data?: TemasekWebApiFeaturesRoomsScheduleUpdateEndpointMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/api/rooms/:roomId/schedule`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}
