/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesPokedexListEndpointQueryResponse, TemasekWebApiFeaturesPokedexListEndpoint401 } from "../types/TemasekWebApiFeaturesPokedexListEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesPokedexListEndpointHandlerResponse204(data?: TemasekWebApiFeaturesPokedexListEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function temasekWebApiFeaturesPokedexListEndpointHandlerResponse401(data?: TemasekWebApiFeaturesPokedexListEndpoint401) {

      return new Response(JSON.stringify(data), {
        status: 401,
        
      })
}

export function temasekWebApiFeaturesPokedexListEndpointHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/pokedex`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}