/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleStreamEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsScheduleStreamEndpointHandlerResponse204(data?: TemasekWebApiFeaturesRoomsScheduleStreamEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function temasekWebApiFeaturesRoomsScheduleStreamEndpointHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/rooms/:roomId/schedule/stream`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}
