/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse } from "../types/TemasekWebApiFeaturesFormSgCallbackEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesFormSgCallbackEndpointHandlerResponse204(data?: TemasekWebApiFeaturesFormSgCallbackEndpointMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function temasekWebApiFeaturesFormSgCallbackEndpointHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/formsg/callback`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}