/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesEnabledFeaturesGetEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesEnabledFeaturesGetEndpointHandlerResponse200(data: TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesEnabledFeaturesGetEndpointHandler(data?: TemasekWebApiFeaturesEnabledFeaturesGetEndpointQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/enabled-features`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}