/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardUpdateEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsSignboardUpdateEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsSignboardUpdateEndpointHandler(data?: TemasekWebApiFeaturesRoomsSignboardUpdateEndpointMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/api/rooms/:roomId/signboard`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}