/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsSignboardGetEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsSignboardGetEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsSignboardGetEndpointHandler(data?: TemasekWebApiFeaturesRoomsSignboardGetEndpointQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/rooms/:roomId/signboard`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}