/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse } from "../types/TemasekWebApiFeaturesRoomsScheduleGetEndpoint.ts";
import { http } from "msw";

export function temasekWebApiFeaturesRoomsScheduleGetEndpointHandlerResponse200(data: TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function temasekWebApiFeaturesRoomsScheduleGetEndpointHandler(data?: TemasekWebApiFeaturesRoomsScheduleGetEndpointQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/api/rooms/:roomId/schedule`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}
